version: "3"

services:
  inventory:
    container_name: inventory
    build:
      context: .
      dockerfile: .docker/inventory/Dockerfile
    volumes:
      - ./inventory:/usr/src/inventory
    depends_on:
      - postgres
      - postgres-replica
    ports:
      - "8000:8000"
  
  inventory-replica1:
    container_name: inventory_replica1
    build:
      context: .
      dockerfile: .docker/inventory/Dockerfile
    volumes:
      - ./inventory:/usr/src/inventory
    depends_on:
      - postgres
      - postgres-replica
    ports:
      - "8001:8000"

  inventory-replica2:
    container_name: inventory_replica2
    build:
      context: .
      dockerfile: .docker/inventory/Dockerfile
    volumes:
      - ./inventory:/usr/src/inventory
    depends_on:
      - postgres
      - postgres-replica
    ports:
      - "8002:8000"

  postgres:
    image: bitnami/postgresql:14
    env_file:
      - ./.docker/postgres/master.env
    volumes:
      - postgres14:/bitnami/postgresql
    ports:
      - "5432"

  postgres-replica:
    image: bitnami/postgresql:14
    env_file:
      - ./.docker/postgres/replica.env
    depends_on:
      - postgres
    ports:
      - "5432"

  nginx:
    image: nginx
    depends_on:
      - inventory
      - inventory-replica1
      - inventory-replica2
    env_file:
      - ./.docker/nginx/nginx.env
    volumes:
      - ./.docker/nginx/templates:/etc/nginx/templates
    ports:
      - "8080:80"

volumes:
  postgres14: